//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEC1G3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor
    {
        public string InstructorID { get; set; }
        public string InstructorFirstName { get; set; }
        public string InstructorLastName { get; set; }
        public string InstructorPhone { get; set; }
        public System.DateTime InstructorHireDate { get; set; }
    
        public virtual TeachingAssignment TeachingAssignment { get; set; }
    }
}
